-- DROP DATABASE IF ALREADY ALREADY EXISTS

DROP SCHEMA IF EXISTS `restaurantdb` ;

-- CREATE DATABASE

CREATE SCHEMA IF NOT EXISTS `restaurantdb`;

USE restaurantdb;

-- RECREATE TABLES

DROP TABLE IF EXISTS Employee ;

CREATE TABLE IF NOT EXISTS Employee 
(
EmployeeID INT NOT NULL AUTO_INCREMENT,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
DOB Date NOT NULL,
Gender Varchar(10) NOT NULL,
Email VARCHAR(255) NOT NULL,
ContactNo VARCHAR(20) NOT NULL,
Salary FLOAT NOT NULL,
Address VARCHAR(255) NOT NULL,
NationalID VARCHAR(50) NOT NULL,
JoiningDate DATETIME NOT NULL,
Designation VARCHAR(50),
PRIMARY KEY (EmployeeID)
);


DROP TABLE IF EXISTS Customer ;

CREATE TABLE IF NOT EXISTS Customer 
(
CustomerID INT NOT NULL AUTO_INCREMENT,
FirstName VARCHAR(50) NOT NULL,
LastName VARCHAR(50) NOT NULL,
Email VARCHAR(255) ,
ContactNo VARCHAR(20) ,
Age INT,
PRIMARY KEY (CustomerID)
);


DROP TABLE IF EXISTS Payment ;

CREATE TABLE IF NOT EXISTS Payment 
(
PaymentID INT NOT NULL AUTO_INCREMENT,
PaymentMethod VARCHAR(50) NOT NULL,
CardNum VARCHAR(50) NOT NULL,
AmountDue FLOAT NOT NULL ,
Tip FLOAT ,
OrderID INT,
PRIMARY KEY (PaymentID)
);

DROP TABLE IF EXISTS Reservation ;

CREATE TABLE IF NOT EXISTS Reservation 
(
ReservationID INT NOT NULL AUTO_INCREMENT,
TableNo VARCHAR(20) NOT NULL,
DateAndTIME DATETIME NOT NULL,
TotalGuests INT NOT NULL ,
CustomerID INT,
PRIMARY KEY (ReservationID)
);

DROP TABLE IF EXISTS Orders;

CREATE TABLE IF NOT EXISTS Orders 
(
OrderID INT NOT NULL AUTO_INCREMENT,
OrderDateTime DATETIME NOT NULL,
Dinein ENUM ('1', '0') NOT NULL,
TableNo VARCHAR(20) ,
Nguests INT NOT NULL ,
CookingTime INT,
TotalAmount INT NOT NULL,
CustomerID INT,
EmployeeID INT,
PRIMARY KEY (OrderID)
);


DROP TABLE IF EXISTS Feedback;

CREATE TABLE IF NOT EXISTS Feedback 
(
FeedbackID INT NOT NULL AUTO_INCREMENT,
Service ENUM ('1', '2', '3', '4', '5','6','7','8','9','10') NOT NULL,
Cleanliness ENUM ('1', '2', '3', '4', '5','6','7','8','9','10') NOT NULL,
FoodQuality ENUM ('1', '2', '3', '4', '5','6','7','8','9','10') NOT NULL,
Comments VARCHAR(255) NOT NULL,
Suggestions VARCHAR(255) NOT NULL,
OrderID INT,
PRIMARY KEY (FeedbackID)
);


DROP TABLE IF EXISTS MenuItem;

CREATE TABLE IF NOT EXISTS MenuItem 
(
MenuItemID INT NOT NULL AUTO_INCREMENT,
ItemName VARCHAR(50) NOT NULL,
Price FLOAT NOT NULL,
ItemType VARCHAR(50) NOT NULL,
PRIMARY KEY (MenuItemID)
);


DROP TABLE IF EXISTS OrderMenuItem;
CREATE TABLE IF NOT EXISTS OrderMenuItem 
(
OrderMenuItemID INT NOT NULL AUTO_INCREMENT,
Quantity INT NOT NULL,
OrderID INT NOT NULL,
MenuItemID INT NOT NULL,
PRIMARY KEY (OrderMenuItemID)
);


DROP TABLE IF EXISTS Users;
CREATE TABLE IF NOT EXISTS Users 
(
UserID INT NOT NULL AUTO_INCREMENT,
UserName VARCHAR(50) NOT NULL,
Pass VARCHAR(50) NOT NULL,
EmployeeID INT NOT NULL,
PRIMARY KEY (UserID)
);


-- select * from customer;

